# Generated by Django 4.1.3 on 2022-11-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.hashtag'),
        ),
    ]
