# Generated by Django 4.1.3 on 2022-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_rename_tittle_post_title_post_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
