# Generated by Django 4.1.3 on 2022-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_hashtag_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(null=True, to='posts.hashtag'),
        ),
    ]
